//! Integrity of the bundled toolchain.
//!
//! The manifest is generated by `cargo xtask fetch-toolchain` and **embedded in
//! the application binary**, not shipped inside the bundle. That is the whole
//! point: a file sitting next to the compiler could be edited by whatever edited
//! the compiler, so it would attest to nothing.
//!
//! Two failures matter and they need different advice. A **missing** file is
//! almost always antivirus — QB64-PE's own `fbc.exe`, and the compiler
//! binaries beside it, are known false positives. A **changed** file is not,
//! and should be treated as tampering.
//!
//! One exception, and it is written down rather than assumed: QB64-PE compiles
//! its own runtime on first use and keeps its settings and its intermediate
//! C++ inside its own directory. Those paths are listed in the manifest as
//! `# mutable: <glob>` by the fetch that wrote it, and are not checked. The
//! list comes with the manifest — embedded in the application, like the
//! hashes — so a file beside the compiler cannot add to it.

use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::io::Read;
use std::path::Path;

#[derive(Debug, Clone, Default)]
pub struct Manifest {
    /// Bundle-relative path (always `/`-separated) to expected SHA-256.
    entries: BTreeMap<String, String>,
    /// Paths the bundle's own compiler writes as it works, which are
    /// therefore not attested. Globs, `/`-separated.
    mutable: Vec<String>,
}

impl Manifest {
    /// Parse `<sha256>  <relative path>` lines. Blank lines and `#` comments are
    /// ignored, so a placeholder manifest in a development checkout parses to
    /// nothing rather than failing.
    pub fn parse(text: &str) -> Self {
        let mut entries = BTreeMap::new();
        let mut mutable = Vec::new();
        for line in text.lines() {
            let line = line.trim();
            if let Some(glob) = line.strip_prefix("# mutable:") {
                let glob = glob.trim();
                if !glob.is_empty() {
                    mutable.push(glob.replace('\\', "/"));
                }
                continue;
            }
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((hash, path)) = line.split_once(char::is_whitespace) else {
                continue;
            };
            let hash = hash.trim();
            let path = path.trim();
            if hash.len() == 64 && hash.bytes().all(|b| b.is_ascii_hexdigit()) && !path.is_empty() {
                entries.insert(path.replace('\\', "/"), hash.to_ascii_lowercase());
            }
        }
        Self { entries, mutable }
    }

    /// Is this bundle-relative path one the compiler writes itself?
    pub fn is_mutable(&self, rel: &str) -> bool {
        self.mutable.iter().any(|g| crate::glob::matches(g, rel))
    }

    pub fn mutable_globs(&self) -> &[String] {
        &self.mutable
    }

    /// A short name for exactly this manifest: what a copy of the compiler is
    /// stamped with, so a copy made from a different one is not reused.
    pub fn digest(&self) -> String {
        let mut h = Sha256::new();
        for (path, hash) in &self.entries {
            h.update(path.as_bytes());
            h.update(hash.as_bytes());
        }
        for g in &self.mutable {
            h.update(g.as_bytes());
        }
        format!("{:x}", h.finalize())[..16].to_string()
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Hash every listed file under `root` and report what does not match.
    pub fn verify(&self, root: &Path) -> VerifyReport {
        let mut report = VerifyReport {
            unattested: false,
            checked: 0,
            missing: Vec::new(),
            changed: Vec::new(),
            unreadable: Vec::new(),
        };
        for (rel, want) in &self.entries {
            if self.is_mutable(rel) {
                continue;
            }
            let path = root.join(rel);
            match hash_file(&path) {
                Ok(Some(got)) => {
                    report.checked += 1;
                    if &got != want {
                        report.changed.push(rel.clone());
                    }
                }
                Ok(None) => report.missing.push(rel.clone()),
                Err(e) => report.unreadable.push((rel.clone(), e.to_string())),
            }
        }
        report
    }
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct VerifyReport {
    pub checked: usize,
    pub missing: Vec<String>,
    pub changed: Vec<String>,
    pub unreadable: Vec<(String, String)>,
    /// A compiler was shipped with this application and there is nothing to
    /// check it against.
    ///
    /// Not the same as "nothing to check". The manifest is generated by the
    /// toolchain fetch and embedded at compile time, so a build that ships a
    /// compiler and an empty manifest was built in the wrong order — and it
    /// cannot tell a tampered compiler from an intact one. Treating that as a
    /// pass is the quiet failure worth refusing: it looks exactly like success.
    pub unattested: bool,
}

impl VerifyReport {
    pub fn is_ok(&self) -> bool {
        !self.unattested
            && self.missing.is_empty()
            && self.changed.is_empty()
            && self.unreadable.is_empty()
    }

    /// Which i18n key explains this failure. A missing file and an altered file
    /// mean very different things and deserve different advice.
    pub fn explanation_key(&self) -> Option<&'static str> {
        if self.unattested {
            Some("toolchain.integrity.unattested")
        } else if !self.changed.is_empty() {
            Some("toolchain.integrity.changed")
        } else if !self.missing.is_empty() {
            Some("toolchain.integrity.missing")
        } else if !self.unreadable.is_empty() {
            Some("toolchain.integrity.unreadable")
        } else {
            None
        }
    }

    /// A short, copyable summary for a support report.
    pub fn detail(&self) -> String {
        let mut s = String::new();
        let mut show = |label: &str, items: &[String]| {
            if items.is_empty() {
                return;
            }
            s.push_str(&format!("{label} ({}):\n", items.len()));
            for i in items.iter().take(10) {
                s.push_str(&format!("  {i}\n"));
            }
            if items.len() > 10 {
                s.push_str(&format!("  … and {} more\n", items.len() - 10));
            }
        };
        show("missing", &self.missing);
        show("changed", &self.changed);
        if !self.unreadable.is_empty() {
            s.push_str(&format!("unreadable ({}):\n", self.unreadable.len()));
            for (p, e) in self.unreadable.iter().take(10) {
                s.push_str(&format!("  {p}: {e}\n"));
            }
        }
        s
    }
}

/// `Ok(None)` means the file is simply not there.
fn hash_file(path: &Path) -> std::io::Result<Option<String>> {
    let mut f = match std::fs::File::open(path) {
        Ok(f) => f,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(e) => return Err(e),
    };
    let mut hasher = Sha256::new();
    let mut buf = vec![0u8; 1 << 16];
    loop {
        let n = f.read(&mut buf)?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    Ok(Some(format!("{:x}", hasher.finalize())))
}

#[cfg(test)]
mod tests {
    #[test]
    fn what_the_compiler_writes_itself_is_not_tampering() {
        let td = tempfile::tempdir().unwrap();
        let a = write(td.path(), "fbc", b"driver");
        write(td.path(), "internal/c/qbx.o", b"built here");
        write(td.path(), "settings/config.ini", b"changed by fbc");
        let m = Manifest::parse(&format!(
            "# mutable: internal/c/*.o\n# mutable: settings/*\n\
             {a}  fbc\n\
             0000000000000000000000000000000000000000000000000000000000000000  internal/c/qbx.o\n\
             0000000000000000000000000000000000000000000000000000000000000000  settings/config.ini\n"
        ));
        assert!(m.is_mutable("internal/c/qbx.o"));
        assert!(m.is_mutable("settings/config.ini"));
        assert!(!m.is_mutable("fbc"));

        let r = m.verify(td.path());
        assert!(r.is_ok(), "{r:?}");
        assert_eq!(r.checked, 1, "only the file that is ours to attest to");
    }

    use super::*;

    fn write(dir: &Path, rel: &str, body: &[u8]) -> String {
        let p = dir.join(rel);
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        std::fs::write(&p, body).unwrap();
        format!("{:x}", Sha256::digest(body))
    }

    #[test]
    fn a_placeholder_manifest_parses_to_nothing() {
        // A development checkout has no real manifest; that must not be an error.
        let m = Manifest::parse("# generated by the fetch task\n\n");
        assert!(m.is_empty());
        assert!(m.verify(Path::new("/nonexistent")).is_ok());
    }

    #[test]
    fn a_matching_tree_verifies() {
        let td = tempfile::tempdir().unwrap();
        let a = write(td.path(), "fbc", b"driver");
        let b = write(td.path(), "internal/c/libqb.cpp", b"the runtime");
        let m = Manifest::parse(&format!("{a}  fbc\n{b}  internal/c/libqb.cpp\n"));
        assert_eq!(m.len(), 2);

        let r = m.verify(td.path());
        assert!(r.is_ok(), "{r:?}");
        assert_eq!(r.checked, 2);
        assert!(r.explanation_key().is_none());
    }

    #[test]
    fn a_removed_file_is_reported_as_missing_not_as_tampering() {
        // The overwhelmingly likely cause is antivirus, and the advice differs.
        let td = tempfile::tempdir().unwrap();
        let a = write(td.path(), "fbc", b"driver");
        let m = Manifest::parse(&format!("{a}  fbc\n{a}  internal/c/libqb.cpp\n"));

        let r = m.verify(td.path());
        assert!(!r.is_ok());
        assert_eq!(r.missing, vec!["internal/c/libqb.cpp".to_string()]);
        assert!(r.changed.is_empty());
        assert_eq!(r.explanation_key(), Some("toolchain.integrity.missing"));
    }

    #[test]
    fn an_altered_file_is_reported_as_changed() {
        let td = tempfile::tempdir().unwrap();
        let a = write(td.path(), "fbc", b"driver");
        let m = Manifest::parse(&format!("{a}  fbc\n"));
        std::fs::write(td.path().join("fbc"), b"something else").unwrap();

        let r = m.verify(td.path());
        assert!(!r.is_ok());
        assert_eq!(r.changed, vec!["fbc".to_string()]);
        assert!(r.missing.is_empty());
        assert_eq!(r.explanation_key(), Some("toolchain.integrity.changed"));
    }

    #[test]
    fn tampering_outranks_a_missing_file_in_the_explanation() {
        let td = tempfile::tempdir().unwrap();
        let a = write(td.path(), "a", b"x");
        let m = Manifest::parse(&format!("{a}  a\n{a}  gone\n"));
        std::fs::write(td.path().join("a"), b"y").unwrap();
        let r = m.verify(td.path());
        assert_eq!(r.explanation_key(), Some("toolchain.integrity.changed"));
    }

    #[test]
    fn malformed_lines_are_skipped_rather_than_poisoning_the_manifest() {
        let m = Manifest::parse(
            "not-a-hash  bin/x\n\
             deadbeef  too-short\n\
             abc  \n\
             \n\
             0000000000000000000000000000000000000000000000000000000000000000  bin/ok\n",
        );
        assert_eq!(m.len(), 1);
        assert!(m.entries.contains_key("bin/ok"));
    }

    #[test]
    fn windows_separators_in_a_manifest_are_normalised() {
        let m = Manifest::parse(
            "0000000000000000000000000000000000000000000000000000000000000000  bin\\fbc.exe\n",
        );
        assert!(m.entries.contains_key("bin/fbc.exe"));
    }

    #[test]
    fn hashes_compare_case_insensitively() {
        let td = tempfile::tempdir().unwrap();
        let a = write(td.path(), "f", b"body").to_uppercase();
        let m = Manifest::parse(&format!("{a}  f\n"));
        assert!(m.verify(td.path()).is_ok());
    }

    #[test]
    fn the_detail_report_is_bounded_for_a_wholesale_failure() {
        // A quarantined bundle can lose hundreds of files; the report has to stay
        // small enough to paste into a message.
        let mut lines = String::new();
        for i in 0..500 {
            lines.push_str(&format!(
                "0000000000000000000000000000000000000000000000000000000000000000  f{i}\n"
            ));
        }
        let td = tempfile::tempdir().unwrap();
        let r = Manifest::parse(&lines).verify(td.path());
        assert_eq!(r.missing.len(), 500);
        let d = r.detail();
        assert!(d.contains("and 490 more"), "{d}");
        assert!(d.len() < 1000);
    }
}
