//! Embed the Windows resources: the application icon, and the version block.
//!
//! Only Windows has a notion of an icon compiled into the executable. Every
//! other platform gets its icon at runtime from `ViewportBuilder::with_icon`,
//! which this build script has nothing to do with.

fn main() {
    println!("cargo:rerun-if-changed=../../packaging/windows/icon.ico");
    println!("cargo:rerun-if-env-changed=ETB_REQUIRE_ICON");

    // Whether the *program* is for Windows, not whether this build script is
    // running on one. `#[cfg(windows)]` asks about the host, so a cross-build
    // from Linux -- which is how the installer is made anywhere but CI --
    // skipped the icon silently, and skipped the `ETB_REQUIRE_ICON` check that
    // exists to catch exactly that. `winresource` drives the mingw resource
    // compiler (`x86_64-w64-mingw32-windres`) when the host is not Windows.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    {
        let icon = std::path::Path::new("../../packaging/windows/icon.ico");
        if !icon.is_file() {
            // Not fatal in an ordinary build. The icon is generated by
            // `cargo xtask gen-icons`, and a checkout that has not run it should
            // still build a working program -- but a release with no icon is the
            // bug ETB_REQUIRE_ICON exists to stop, and a missing file is one of
            // the two ways to arrive there.
            let msg = format!("no icon at {}; run `cargo xtask gen-icons`", icon.display());
            if std::env::var_os("ETB_REQUIRE_ICON").is_some() {
                panic!("{msg}");
            }
            println!("cargo:warning={msg}");
            return;
        }
        let mut res = winresource::WindowsResource::new();
        res.set_icon(&icon.to_string_lossy());
        res.set("ProductName", "Easy Turbo Basic");
        res.set("FileDescription", "Easy Turbo Basic");
        if let Err(e) = res.compile() {
            // The resource compiler is part of the Windows SDK, and its absence
            // should cost an icon rather than a build -- unless this is a
            // release, where a missing icon is the bug being guarded against.
            let msg = format!("could not embed the icon: {e}");
            if std::env::var_os("ETB_REQUIRE_ICON").is_some() {
                panic!("{msg}");
            }
            println!("cargo:warning={msg}");
        }
    }
}
