#!/usr/bin/env bash
# Exercise the Windows FreeBASIC bundle from Linux, under wine.
#
# The Windows bundle is fetched on Linux, where its binaries cannot run, so
# without this there is nothing between "the files look right" and "Windows CI
# said so". wine is not Windows and a pass here is not proof — but it catches
# the things that would otherwise reach CI. On the day it was first run it
# showed that a Windows compiler takes its arguments through the ANSI code
# page: a Vietnamese path arrived as `Nguy?n Van A`.
#
# Usage:  toolchain/verify-under-wine.sh
set -euo pipefail

command -v wine >/dev/null || { echo "wine is not installed"; exit 1; }

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
bundle="$repo/target/toolchain/windows-x86_64"
prefix="${ETB_WINEPREFIX:-$repo/target/wineprefix}"

if [ ! -d "$bundle" ]; then
  echo "fetching the bundle first"
  (cd "$repo" && cargo xtask fetch-toolchain --target windows-x86_64)
fi

if [ ! -d "$prefix" ]; then
  echo "creating a wine prefix at $prefix (not your ~/.wine)"
  WINEPREFIX="$prefix" WINEDEBUG=-all wineboot -i >/dev/null 2>&1 || true
fi

# The manifest goes back to its committed placeholder first. This script edits
# the bundle's own `bundle.toml` to add the launcher below, so a manifest
# generated by the last fetch would — correctly — report the bundle as altered
# and every build would be refused. A checkout's normal state is the
# placeholder; the generated one belongs to packaging.
git -C "$repo" checkout -- crates/etb-gui/assets/toolchain-manifest.txt 2>/dev/null || true

# A shipped bundle runs natively and carries none of this. Appending it here
# rather than putting it in the template keeps the cross-testing arrangement out
# of what users receive — and `cargo xtask package` refuses a bundle that has it.
if ! grep -q '^launcher' "$bundle/bundle.toml"; then
  cat >> "$bundle/bundle.toml" <<TOML

# Added by verify-under-wine.sh. Cross-testing from Linux only.
launcher = "wine"

[env]
# The child environment is scrubbed to an allowlist, so wine would otherwise
# lose its prefix and quietly build a fresh one in \$HOME.
WINEPREFIX = "$prefix"
WINEDEBUG = "-all"
XDG_RUNTIME_DIR = "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
TOML
fi

echo
echo "== the compiler, through wine =="
ETB_TOOLCHAIN_BUNDLE="$bundle" \
  cargo run -q -p etb-cli --manifest-path "$repo/Cargo.toml" -- doctor

echo
echo "== the whole corpus, built and run through wine =="
cd "$repo"
ETB_REQUIRE_TOOLCHAIN=1 ETB_TOOLCHAIN_BUNDLE="$bundle" \
  cargo test -p etb-testkit --test corpus -- --nocapture --test-threads=1

echo
echo "== a compiler installed under a Vietnamese user name =="
# This is where the ANSI code page problem was first seen, so this is where the
# answer to it is exercised. It copies the bundle, so it is not part of the run
# above.
ETB_TOOLCHAIN_BUNDLE="$bundle" \
  cargo test -p etb-testkit --test bundle -- --ignored --nocapture vietnamese
